from datetime import datetime
from pydantic import BaseModel, EmailStr, Field, ConfigDict, field_validator


# ─────────────────────────────────────────────────────────────────────────────
# UserCreate — validates data received when a new user registers.
#
# Fields:
#   name     → Required. The user's display name.
#   email    → Required. Must be a valid email format (validated by EmailStr).
#   password → Required. Must be at minimum 8 characters for basic security.
#
# Why no 'id', 'created_at', or 'updated_at'?
#   These are auto-generated by the database. The client never sends them.
#
# Why is password here but not in UserResponse?
#   We need the raw password from the client to hash it before storing.
#   But once stored, we never expose the hash back through the API.
# ─────────────────────────────────────────────────────────────────────────────
class UserCreate(BaseModel):
    name: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Full name of the user",
        examples=["John Doe"]
    )
    email: EmailStr = Field(
        ...,
        description="Valid email address used for login",
        examples=["john@example.com"]
    )
    password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description="Password must be at least 8 characters",
        examples=["securePass123"]
    )

    @field_validator("name")
    @classmethod
    def name_must_not_be_blank(cls, v: str) -> str:
        """Ensure name is not just whitespace."""
        if not v.strip():
            raise ValueError("Name must not be blank or whitespace only")
        return v.strip()

    @field_validator("password")
    @classmethod
    def password_strength(cls, v: str) -> str:
        """
        Basic password strength check.
        In production, you may integrate zxcvbn or a dedicated validator.
        """
        if v.isdigit():
            raise ValueError("Password must not consist of numbers only")
        if v.isalpha():
            raise ValueError("Password must contain at least one number or special character")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# UserLogin — validates credentials submitted at the login endpoint.
#
# Fields:
#   email    → Required. The registered email address.
#   password → Required. The raw plaintext password to verify against hash.
#
# Why is this a separate schema from UserCreate?
#   Login only needs email + password. Having a dedicated schema makes the
#   API contract explicit and prevents accidental field leakage.
# ─────────────────────────────────────────────────────────────────────────────
class UserLogin(BaseModel):
    email: EmailStr = Field(
        ...,
        description="Registered email address",
        examples=["john@example.com"]
    )
    password: str = Field(
        ...,
        min_length=1,
        description="Account password",
        examples=["securePass123"]
    )


# ─────────────────────────────────────────────────────────────────────────────
# UserResponse — the shape of user data returned to the client.
#
# Fields:
#   id         → The unique identifier of the user record.
#   name       → Display name.
#   email      → The registered email.
#   created_at → When the account was created.
#   updated_at → When the account was last modified.
#
# Why no 'password' field?
#   Never expose password hashes through the API. Even hashed passwords
#   can be brute-forced offline if leaked. Omitting the field entirely
#   from the response schema is the only safe approach.
#
# ConfigDict(from_attributes=True):
#   Allows Pydantic to read data from SQLAlchemy ORM objects using getattr().
#   Without this, UserResponse.model_validate(user_orm) would raise a TypeError
#   because Pydantic would try dict-style access on an ORM object.
# ─────────────────────────────────────────────────────────────────────────────
class UserResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    email: EmailStr
    created_at: datetime
    updated_at: datetime
